#remove student
from Tkinter import *
root= Tk()
def bye():
    root.destroy()

def entry_box():
    def bye():
        root.destroy()
    root=Tk()
    Label(root,text="DETAILS").grid(row=0,column=2)
    Label(root,text="Class").grid(row=2,column=0)
    clas=Entry(root)
    clas.grid(row=2,column=1)
    Label(root,text="Section").grid(row=2,column=3)
    sec=Entry(root)
    sec.grid(row=2,column=4)
    Label(root,text="PERSONAL DETAILS").grid(row=3,column=0)
    Label(root,text="ADDNo").grid(row=4,column=0)
    addno=Entry(root)
    addno.grid(row=4,column=1)
    Label(root,text="First name").grid(row=5,column=0)
    fname=Entry(root)
    fname.grid(row=5,column=1)
    Label(root,text="Last name").grid(row=5,column=3)
    lname=Entry(root)
    lname.grid(row=5,column=4)
    Label(root,text="Father's name").grid(row=6,column=0)
    fname=Entry(root)
    fname.grid(row=6,column=1)
    Label(root,text="Mother's Name").grid(row=6,column=3)
    mname=Entry(root)
    mname.grid(row=6,column=4)
    Label(root,text="DOB").grid(row=7,column=0)
    dob=Entry(root)
    dob.grid(row=7,column=1)
    Label(root,text="CONTACT DETAILS").grid(row=9,column=0)
    Label(root,text="Address").grid(row=10,column=0)
    add=Entry(root)
    add.grid(row=10,column=1)
    
    Label(root,text="tel no").grid(row=11,column=0)
    tel=Entry(root)
    tel.grid(row=11,column=1)
    Label(root,text="mobile no").grid(row=11,column=3)
    mno=Entry(root)
    mno.grid(row=11,column=4)
    Label(root,text="Email ID").grid(row=11,column=0)
    email=Entry(root)
    email.grid(row=11,column=1)
    Label(root,text="ID proof").grid(row=12,column=0)
    idp=Entry(root)
    idp.grid(row=12,column=1)
    Label(root,text="SUBJECT OPTED").grid(row=13,column=0)
    Label(root,text="Code").grid(row=14,column=0)
    c1=Button(root,text="1",fg="blue",bg="yellow").grid(row=14,column=1)
    c2=Button(root,text="2",fg="blue",bg="yellow").grid(row=14,column=2)
    c3=Button(root,text="3",fg="blue",bg="yellow").grid(row=14,column=3)
    c4=Button(root,text="4",fg="blue",bg="yellow").grid(row=14,column=4)
    remove=Button(root,text="Remove",fg="white",bg="black").grid(row=30,column=0)
    cancel=Button(root,text="Cancel",fg="white",bg="black",command=bye).grid(row=30,column=3)


    

Label(root,text="Class").grid(row=0,column=0)
clas=Entry(root)
clas.grid(row=0,column=1)
Label(root,text="Student Name").grid(row=2,column=0)
sname=Entry(root)
sname.grid(row=2,column=1)
Label(root,text="Section").grid(row=4,column=0)
sec=Entry(root)
sec.grid(row=4,column=1)
getdetails=Button(root,text="Get Details",fg="white",bg="black",command=entry_box).grid(row=6,column=0)
cancel=Button(root,text="Cancel",fg="white",bg="black",command=bye).grid(row=6,column=1)
mainloop()

